[package]
name = "schedule1-mixing"
version = "0.1.0"
edition = "2021"

[lib]
name = "schedule1"
path = "src/lib.rs"

[[bin]]
name = "schedule1-mixing-tool"
path = "src/bin.rs"

[dependencies]
bitflags = "2.9.0"
clap = { version = "4.5.36", features = ["derive"] }
crossbeam = "0.8.4"
indicatif = { version = "0.17.11", features = ["rayon"] }
lockfree-object-pool = "0.1.6"
num_cpus = "1.16.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
topological-sort = "0.2.2"
topset = "0.4.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "dfs"
harness = false
